-- Bootstrap schema for The Soft Wave on a fresh Supabase project
-- Run this in Supabase SQL Editor for project: mbecdcimfjodnjihfmwz

create extension if not exists pgcrypto;

-- ============================================================
-- PLAYLISTS
-- ============================================================
create table if not exists public.playlists (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  mood text not null default '',
  tracks jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists playlists_user_id_idx on public.playlists(user_id);
create index if not exists playlists_created_at_idx on public.playlists(created_at desc);

alter table public.playlists enable row level security;

drop policy if exists playlists_select_own on public.playlists;
create policy playlists_select_own
on public.playlists
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists playlists_insert_own on public.playlists;
create policy playlists_insert_own
on public.playlists
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists playlists_update_own on public.playlists;
create policy playlists_update_own
on public.playlists
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists playlists_delete_own on public.playlists;
create policy playlists_delete_own
on public.playlists
for delete
to authenticated
using (auth.uid() = user_id);

-- ============================================================
-- FAVORITES
-- ============================================================
create table if not exists public.favorites (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  artist_id text not null,
  created_at timestamptz not null default now(),
  unique (user_id, artist_id)
);

create index if not exists favorites_user_id_idx on public.favorites(user_id);
create index if not exists favorites_artist_id_idx on public.favorites(artist_id);

alter table public.favorites enable row level security;

drop policy if exists favorites_select_own on public.favorites;
create policy favorites_select_own
on public.favorites
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists favorites_insert_own on public.favorites;
create policy favorites_insert_own
on public.favorites
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists favorites_delete_own on public.favorites;
create policy favorites_delete_own
on public.favorites
for delete
to authenticated
using (auth.uid() = user_id);

-- ============================================================
-- CHAT MESSAGES
-- ============================================================
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_user_id_idx on public.chat_messages(user_id);
create index if not exists chat_messages_created_at_idx on public.chat_messages(created_at asc);

alter table public.chat_messages enable row level security;

drop policy if exists chat_messages_select_own on public.chat_messages;
create policy chat_messages_select_own
on public.chat_messages
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists chat_messages_insert_own on public.chat_messages;
create policy chat_messages_insert_own
on public.chat_messages
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists chat_messages_delete_own on public.chat_messages;
create policy chat_messages_delete_own
on public.chat_messages
for delete
to authenticated
using (auth.uid() = user_id);

-- ============================================================
-- RECOMMENDER EVENTS (learning loop telemetry)
-- ============================================================
create table if not exists public.recommendation_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id text not null,
  event_type text not null,
  source text,
  mood text,
  artist_id text,
  artist_name text,
  track_name text,
  rank_score double precision,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists recommendation_events_user_id_idx
  on public.recommendation_events(user_id);
create index if not exists recommendation_events_event_type_idx
  on public.recommendation_events(event_type);
create index if not exists recommendation_events_created_at_idx
  on public.recommendation_events(created_at desc);

alter table public.recommendation_events enable row level security;

drop policy if exists recommendation_events_select_own on public.recommendation_events;
create policy recommendation_events_select_own
on public.recommendation_events
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists recommendation_events_insert_own on public.recommendation_events;
create policy recommendation_events_insert_own
on public.recommendation_events
for insert
to authenticated
with check (auth.uid() = user_id);

-- ============================================================
-- TRACK MISMATCH REPORTS (global correction memory)
-- ============================================================
create table if not exists public.track_mismatch_reports (
  id bigint generated by default as identity primary key,
  reporter_user_id uuid not null references auth.users(id) on delete cascade,
  artist_name text not null,
  track_name text not null,
  source text,
  reason text,
  expected_artist_name text,
  expected_track_name text,
  created_at timestamptz not null default now()
);

create index if not exists track_mismatch_reports_lookup_idx
  on public.track_mismatch_reports(artist_name, track_name);
create index if not exists track_mismatch_reports_created_at_idx
  on public.track_mismatch_reports(created_at desc);

alter table public.track_mismatch_reports enable row level security;

drop policy if exists track_mismatch_reports_select_all on public.track_mismatch_reports;
create policy track_mismatch_reports_select_all
on public.track_mismatch_reports
for select
to authenticated
using (true);

drop policy if exists track_mismatch_reports_insert_own on public.track_mismatch_reports;
create policy track_mismatch_reports_insert_own
on public.track_mismatch_reports
for insert
to authenticated
with check (auth.uid() = reporter_user_id);

-- ============================================================
-- ACCOUNT API KEYS
-- ============================================================
create table if not exists public.user_api_keys (
  user_id uuid primary key references auth.users(id) on delete cascade,
  provider text not null check (provider in ('openrouter', 'gemini')),
  api_key text not null,
  selected_model text,
  updated_at timestamptz not null default now()
);

alter table public.user_api_keys enable row level security;

drop policy if exists user_api_keys_select_own on public.user_api_keys;
create policy user_api_keys_select_own
on public.user_api_keys
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists user_api_keys_insert_own on public.user_api_keys;
create policy user_api_keys_insert_own
on public.user_api_keys
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists user_api_keys_update_own on public.user_api_keys;
create policy user_api_keys_update_own
on public.user_api_keys
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists user_api_keys_delete_own on public.user_api_keys;
create policy user_api_keys_delete_own
on public.user_api_keys
for delete
to authenticated
using (auth.uid() = user_id);

-- ============================================================
-- TRACK RATINGS
-- ============================================================
create table if not exists public.track_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  artist_name text not null,
  track_name text not null,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, artist_name, track_name)
);

create index if not exists track_ratings_user_id_idx
  on public.track_ratings(user_id);
create index if not exists track_ratings_track_lookup_idx
  on public.track_ratings(artist_name, track_name);
create index if not exists track_ratings_created_at_idx
  on public.track_ratings(created_at desc);

alter table public.track_ratings enable row level security;

drop policy if exists track_ratings_select_own on public.track_ratings;
create policy track_ratings_select_own
on public.track_ratings
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists track_ratings_insert_own on public.track_ratings;
create policy track_ratings_insert_own
on public.track_ratings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists track_ratings_update_own on public.track_ratings;
create policy track_ratings_update_own
on public.track_ratings
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists track_ratings_delete_own on public.track_ratings;
create policy track_ratings_delete_own
on public.track_ratings
for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.track_rating_stats (
  artist_name text not null,
  track_name text not null,
  rating_count integer not null default 0,
  rating_avg numeric(4,2) not null default 0,
  updated_at timestamptz not null default now(),
  primary key (artist_name, track_name)
);

alter table public.track_rating_stats enable row level security;

drop policy if exists track_rating_stats_select_all on public.track_rating_stats;
create policy track_rating_stats_select_all
on public.track_rating_stats
for select
to authenticated
using (true);

create or replace function public.refresh_track_rating_stats() returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_artist text;
  v_track text;
begin
  if (TG_OP = 'DELETE') then
    v_artist := OLD.artist_name;
    v_track := OLD.track_name;
  else
    v_artist := NEW.artist_name;
    v_track := NEW.track_name;
  end if;

  insert into public.track_rating_stats (artist_name, track_name, rating_count, rating_avg, updated_at)
  select
    v_artist,
    v_track,
    count(*)::int as rating_count,
    coalesce(round(avg(rating)::numeric, 2), 0) as rating_avg,
    now()
  from public.track_ratings
  where artist_name = v_artist and track_name = v_track
  on conflict (artist_name, track_name) do update
    set rating_count = excluded.rating_count,
        rating_avg = excluded.rating_avg,
        updated_at = now();

  delete from public.track_rating_stats
  where artist_name = v_artist and track_name = v_track and rating_count <= 0;

  return null;
end;
$$;

drop trigger if exists trg_refresh_track_rating_stats on public.track_ratings;
create trigger trg_refresh_track_rating_stats
after insert or update or delete on public.track_ratings
for each row execute function public.refresh_track_rating_stats();

-- backfill stats in case ratings already exist
insert into public.track_rating_stats (artist_name, track_name, rating_count, rating_avg, updated_at)
select artist_name, track_name, count(*)::int, round(avg(rating)::numeric, 2), now()
from public.track_ratings
group by artist_name, track_name
on conflict (artist_name, track_name) do update
  set rating_count = excluded.rating_count,
      rating_avg = excluded.rating_avg,
      updated_at = now();

-- ============================================================
-- PRIVILEGES
-- ============================================================
grant usage on schema public to authenticated;
grant select, insert, update, delete on public.playlists to authenticated;
grant select, insert, delete on public.favorites to authenticated;
grant select, insert, delete on public.chat_messages to authenticated;
grant select, insert on public.recommendation_events to authenticated;
grant select, insert, update, delete on public.track_ratings to authenticated;
grant select on public.track_rating_stats to authenticated;
grant select, insert, update, delete on public.user_api_keys to authenticated;
grant usage, select on all sequences in schema public to authenticated;
